### ISSUE TITLE
Not working with Flask-Login >=0.4.0

### ISSUE THREAD

**Issue by A-Dechorgnat** [inkscope/inkscope#96]
`AttributeError: 'LoginManager' object has no attribute 'token_loader'`

see https://github.com/maxcountryman/flask-login/blob/594e5d77c1101a103c76caf46895cea350e14287/CHANGES#L13-L16

**Comment by A-Dechorgnat** [comment]
But still works with Flask-Login==0.3.2
We absolutely need a "requirements.txt"

**Comment by A-Dechorgnat** [comment]
see requirements.txt
